[tool.ruff]
# Enforce a reasonable line length and target Python version.
line-length = 100
target-version = "py311"

# Select common error and style codes: E (pycodestyle errors),
# F (Pyflakes), W (warnings) and I001 (import sorting).  These cover
# most of the issues one would want to address in a small project.
select = ["E", "F", "W", "I001"]

# Exclude the virtual environment and outputs from linting.  Note that
# ``static/outputs`` contains generated PNGs and should not be
# inspected.
exclude = [
  "venv",
  "static/outputs",
  "__pycache__",
]